//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.19 at 09:46:57 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.un4ckn0wl3z.xyz", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package xyz.un4ckn0wl3z;
